version: 0.2 
 
phases: 
    install: 
       runtime-versions: 
           python: 3.7 
    build: 
       commands: 
          - echo Compling has started 
          - chmod 777 Helloworld.py 
          - python Helloworld.py 
    post_build: 
       commands: 
          - echo compiling of process has started 
artifacts: 
    files: 
       - Helloworld.py 
